import os
import re

# Comprehensive dictionary for all Bengali terms and phrases found in the code to Ghanaian Twi (Akan)
TRANSLATIONS = {
    # Language Switcher & Settings
    "বাংলা (Bengali)": "Twi / Akan (Ghana)",
    "সম্পূর্ণ বাংলা ইন্টারফেস": "Kasa titiriw a wɔka wɔ Ghana (Twi/Akan interface)",
    "ভাষা ও ডিসপ্লে সেটিংস": "Kasa & Mfiridwuma Nhyehyɛeɛ",
    "ভাষা ও অঞ্চল": "Kasa & Mmantam",
    "বিজ্ঞপ্তি ও অ্যালার্ট": "Nkaebɔ & Kɔkɔbɔ",
    "ইনভয়েস ও প্রিন্ট": "Invois & Tintim",
    "সিস্টেম ও ডেটা": "Nhyehyɛe & Nsɛm",
    "দোকানের তথ্য": "Dukan Ho Nsɛm",
    "বাংলা": "Twi (Akan)",
    "English": "English",
    "শাখা পরিবর্তন": "Sesa Baa (Select Branch)",
    "নতুন বিক্রয় (POS)": "Tua Ka / POS Foforɔ",
    "অন্যান্য ভিউ": "Hwɛbea Foforɔ (Special Views)",
    "ইনভয়েস ভিউ": "Invois Hwɛbea",
    "মোবাইল বিক্রয়": "Mobaele Tɔn",
    "লাইভ কাস্টমার শপ": "Kastama Dukan",
    "দোকান সেটিংস": "Dukan Nhyehyɛeɛ",
    "রিপোর্ট ও লাভ-ক্ষতি": "Amanneɛbɔ & Mfasoɔ",
    "পণ্য বা গ্রাহক খুঁজুন...": "Hwehwɛ nnoɔma anaa atɔfoɔ...",
    "মেসেজিং ও চ্যাট": "Nkitahodie & Nkɔmbɔ",
    "বিজ্ঞপ্তি": "Nkaebɔ",
    "সব পড়া হয়েছে": "Kenkan ne nyinaa",
    "কোনো নতুন বিজ্ঞপ্তি নেই": "Nkaebɔ foforɔ biara nni hɔ",
    "সব বিজ্ঞপ্তি দেখুন": "Hwɛ nkaebɔ nyinaa",
    "লগআউট": "Pue Wɔ Mu (Logout)",

    # Business types in Settings
    "Grocery / মুদি দোকান": "Grocery & Provisions / Nnoɔma Dukan",
    "Clothing / কাপড়ের দোকান": "Boutique & Fashion / Ntoma & Ntadehyɛ",
    "Electronics / ইলেকট্রনিক্স": "Electronics & Phones / Anyinam Nnoɔma",
    "Pharmacy / ফার্মেসি": "Pharmacy & Chemist / Nnuru Dukan",
    "Cosmetics / কসমেটিক্স": "Cosmetics & Beauty / Ahosiesie Nnoɔma",
    "Wholesale / পাইকারি ব্যবসা": "Wholesale / Nnoɔma Dodoɔ Tɔn",
    "Super Shop / ডিপার্টমেন্টাল": "Supermarket & Mart / Dukan Kɛseɛ",

    # Dashboard & KPIs
    "ব্যবসায়িক ওভারভিউ": "Adwumayɛ Nhwɛso (Overview)",
    "আজ": "Ɛnnɛ",
    "এই সপ্তাহ": "Dapɛn Yi",
    "এই মাস": "Bosome Yi",
    "সোম": "Dwo",
    "মঙ্গল": "Bena",
    "বুধ": "Wuku",
    "বৃহঃ": "Yawo",
    "শুক্র": "Efi",
    "শনি": "Meme",
    "ব্যবসায়িক রেটিং:": "Adwuma Gyinabea:",
    "শীর্ষ বিশ্বস্ত শপ": "Dukan a Wɔgye Di Pa Ara",
    "এনবিআর কর অনুগত": "GRA Tax Compliant",
    "রিভিউ ও রেটিং দেখুন": "Hwɛ Nsɛm a Wɔaka",
    "আজকের মোট বিক্রয়": "Ɛnnɛ Tɔn Nyinaa",
    "গত সপ্তাহের তুলনায়": "sen dapɛn a ɛtwaam",
    "নিট লাভ": "Mfasoɔ Pɔtee",
    "মার্জিন": "Mfasoɔ %",
    "ক্যাশ ও ব্যাংক": "Sika & Sikakorabea",
    "টি অ্যাকাউন্ট": "akawnt",
    "গ্রাহক বকেয়া": "Kastamafoɔ Aka",
    "জন বাকিদার": "atɔfoɔ a wɔde aka",
    "দ্রুত কাজ ও বিশেষ সুবিধাসমূহ": "Nnwuma Ntɛmntɛm",
    "পণ্য যোগ করুন": "Fa Nnoɔma Ka Ho",
    "বাকি আদায়": "Gye Aka No",
    "কর ও ভ্যাট পরিশোধ": "GRA Tax & VAT Tua",
    "কোনটি কেনা উচিত": "Deɛ Ɛsɛ Sɛ Wotɔ (Advisory)",
    "রেটিং ও রিভিউ": "Gyinabea & Nsɛm",
    "মার্কেটিং ও SMS": "Dawubɔ & SMS",
    "কুরিয়ার পার্সেল": "Kɔmafoɔ Parcel",
    "ব্যাংক ও লোন": "Sikakorabea & Bosea",
    "অনলাইন স্টোর": "Intanɛte Dukan",
    "লাভ-ক্ষতি রিপোর্ট": "Mfasoɔ & Amanneɛbɔ",
    "বিক্রয় ও লাভের ট্রেন্ড": "Tɔn & Mfasoɔ Akwankyerɛ",
    "বিক্রয়": "Tɔn",
    "লাভ": "Mfasoɔ",
    "বিভাগ ভিত্তিক পণ্য": "Nkyekyɛmu Nnoɔma",
    "টি পণ্য": "nnoɔma",
    "টি পণ্য পাওয়া গেছে": "nnoɔma a yɛahunu",
    "টি পণ্য রয়েছে": "nnoɔma wɔ hɔ",
    "সাম্প্রতিক বিক্রয় ও ইনভয়েস": "Tɔn a Wɔayɛ Nnansa Yi",
    "নতুন বিক্রয়": "Tɔn Foforɔ",
    "ইনভয়েস": "Invois",
    "গ্রাহক": "Otɔfoɔ",
    "আইটেম": "Nnoɔma",
    "মোট টাকা": "Ne Nyinaa",
    "মাধ্যম": "Kwan a Wɔfaa So",
    "রসিদ": "Kasaa (Receipt)",
    "কোনটি কেনা উচিত (ক্রয় পরামর্শ)": "Deɛ Ɛsɛ Sɛ Wotɔ (Advisory)",
    "বিস্তারিত": "Hwɛ Ne Nyinaa",
    "জরুরি কিনুন": "Tɔ Ntɛmntɛm (Urgent)",
    "শীঘ্রই কিনুন": "Tɔ Bi Ntɛm",
    "শীঘ্রই শেষ হবে": "Ɛrensa Ntɛm",
    "পর্যাপ্ত স্টক": "Akorae Wɔ Hɔ",
    "কম চাহিদা": "Tɔn Ntoasoɔ Brɛoo",
    "জরুরি": "Ntɛmntɛm",
    "শীঘ্রই": "Ɛrensa Ntɛm",
    "নিরাপদ": "Akorae Dɔɔso",
    "এই ক্যাটাগরিতে কোনো পণ্য নেই!": "Nnoɔma biara nhia akorae foforɔ ha!",
    "সাপ্লায়ার অর্ডার তৈরি করুন": "Yɛ Agorɔfoɔ Order",

    # Stock & Inventory Statuses
    "কম স্টক": "Akorae Aka Kakra",
    "স্টক শেষ": "Akorae Asa",
    "স্টক শেষ!": "Akorae Asa!",
    "সর্বোচ্চ স্টক সীমা": "Akorae Boro So",
    "স্টক সীমা": "Akorae Gyinabea",
    "কার্ট খালি": "Kɛntɛn No Da Mpan",
    "পণ্য বা খুঁজুন": "Hwehwɛ nnoɔma...",
    "স্টক আছে": "Akorae Wɔ Hɔ",
    "স্টকে আছে (In Stock)": "Akorae Wɔ Hɔ",
    "স্টক শেষ (Out of Stock)": "Akorae Asa",

    # Mobile Dashboard & POS
    "ক্রয়": "Nnoɔma a Wɔatɔ",
    "পণ্য তালিকা": "Nnoɔma Din",
    "হিসাব খাতা": "Sika Kyerɛwtohɔ",
    "খরচের খাতা": "Ka Kyerɛwtohɔ",
    "গ্রাহক তালিকা": "Atɔfoɔ Din",
    "সাপ্লায়ার": "Agorɔfoɔ",
    "বেচা-বিক্রি": "Tɔn Nnoɔma",
    "স্টক": "Akorae",
    "দেনা-পে": "Aka / Bosea",
    "আরও": "Pii (More)",
    "হোম": "Fie (Home)",
    "কার কাছে কত": "Hwan na ɔde wo",
    "বাকি": "Aka",
    "মনে পড়ছে না?": "Wokae anaa?",
    "বাকির খাতা দেখুন": "Hwɛ Aka Kyerɛwtohɔ",
    "বন্ধ করুন": "To Mu",
    "স্লাইড": "Slide",
    "বিক্রয় সফলভাবে সম্পন্ন!": "Tɔn No Awie Pɛpɛɛpɛ!",
    "ফেরত:": "Nsakyerae:",
    "রসিদ দেখুন ও প্রিন্ট": "Hwɛ Kasaa & Tintim",
    "নতুন বিক্রয় করুন": "Yɛ Tɔn Foforɔ",
    "পরিশোধযোগ্য টাকা": "Ne Nyinaa a Ɛsɛ Sɛ Wotua",
    "নগদ গৃহীত টাকা": "Sika a Wɔagye Pɔtee",

    # Customers & Dues
    "ভিআইপি": "Otɔfo Titiriw (VIP)",
    "নিয়মিত": "Otɔfo Penee",
    "নতুন": "Otɔfo Foforɔ",
    "বাকি আছে": "Aka Wɔ Hɔ",
    "পেছনে যান": "San Kɔ Akyi",
    "নতুন গ্রাহক": "Fa Otɔfoɔ Foforɔ Ka Ho",
    "মোট গ্রাহক": "Atɔfoɔ Nyinaa",
    "নিয়মিত গ্রাহক": "Atɔfoɔ a Wɔba Daa",
    "মোট বকেয়া পাওনা": "Aka Nyinaa",
    "বকেয়াদার গ্রাহক": "Atɔfoɔ a Wɔde Aka",
    "এসএমএস পাঠানো হয়েছে!": "SMS Nkaebɔ Akɔ!",
    "নতুন বাকি এন্ট্রি": "Kyerɛw Aka Foforɔ",
    "মোট বাকি পাওনা": "Aka Nyinaa a Ɛda Hɔ",
    "বাকিদার গ্রাহক": "Atɔfoɔ a Wɔde Aka",
    "বাকি টাকা আদায়": "Gye Aka No",
    "বাকি টাকা জমা": "Gye Aka No",
    "বাকি নেই": "Aka Biara Nni Hɔ",

    # Employees & HR
    "ক্যাশিয়ার": "Cashier",
    "স্টোর ম্যানেজার": "Store Manager",
    "স্টাফ": "Staff",
    "নতুন কর্মচারী": "Fa Adwumayɛfoɔ Foforɔ Ka Ho",
    "মোট কর্মচারী": "Adwumayɛfoɔ Nyinaa",
    "মাসিক মোট বেতন": "Akatua Nyinaa Bosome Biara",
    "বেতন পরিশোধ": "Tua Akatua",
    "কর্মচারীর নাম": "Adwumayɛfoɔ Din",
    "পদবী": "Dibea",
    "যোগদানের তারিখ": "Da a Ɔhyɛɛ Aseɛ",
    "মাসিক বেতন": "Bosome Akatua",

    # Purchases & Suppliers
    "পরিশোধিত": "Wɔatua Pɛpɛɛpɛ",
    "আংশিক বাকি": "Wɔatua Fa Bi",
    "বাকিতে ক্রয়": "Tɔ wɔ Aka So",
    "নতুন ক্রয় অর্ডার": "Purchase Order Foforɔ",
    "মোট ক্রয়": "Nnoɔma a Wɔatɔ Nyinaa",
    "সাপ্লায়ার দেনা": "Agorɔfoɔ Aka",
    "মোট সাপ্লায়ার দেনা": "Agorɔfoɔ Aka Nyinaa",
    "সাপ্লায়ার যোগ করুন": "Fa Agorɔfoɔ Foforɔ Ka Ho",
    "মোট পরিশোধ": "Akatua Nyinaa",

    # Expenses & Cash Accounts
    "দোকান ভাড়া": "Dukan Ka (Shop Rent)",
    "বিদ্যুৎ": "Anyinam Ahoɔden (Electricity)",
    "বেতন": "Akatua (Salary)",
    "পরিবহন": "Kwantuo Ka (Transport)",
    "খাবার": "Aduane (Food)",
    "অন্যান্য": "Nnoɔma Foforɔ (Others)",
    "টাকা ট্রান্সফার করুন": "Mane Sika (Transfer)",
    "ক্যাশ জমা": "Hyɛ Sika Mu",
    "টাকা উত্তোলন": "Yi Sika",
    "ক্যাশ ও হিসাব": "Sika & Akawnt",

    # Marketing & Alerts
    "অপর্যাপ্ত এসএমএস ব্যালেন্স": "SMS Sika Nso Wɔ Akawnt Mu",
    "অনুগ্রহ করে এসএমএস ব্যালেন্স রিচার্জ করুন।": "Yɛsrɛ wo, hyɛ wo SMS akawnt mu sika.",
    "প্রচারণামূলক এসএমএস": "Dawubɔ SMS",
    "ব্যালেন্স": "Sika a Aka",
    "সিস্টেম স্ক্যান সম্পন্ন!": "System Nhwehwɛmu Awie!",
    "এখনই স্ক্যান করুন": "Hwehwɛ Mfiridwuma Mu Seesei",
    "পেন্ডিং অ্যালার্ট": "Kɔkɔbɔ a Ɛda Hɔ",
    "অ্যাক্টিভ রুলস": "Mmara a Ɛreyɛ Adwuma",

    # Invoice & Receipts
    "পিডিএফ ডাউনলোড সম্পন্ন হয়েছে!": "PDF No Atwe Awie!",
    "ইনভয়েস লিঙ্ক পাঠানো হয়েছে!": "Wɔamane Invois Link No!",
    "বিক্রয় রসিদ ও ইনভয়েস": "Tɔn Tekiti & Invois",
    "শেয়ার": "Kyɛ",
    "পিডিএফ": "PDF",
    "প্রিন্ট": "Tintim",
    "সর্বমোট টাকা:": "NE NYINAA PƐPƐƐPƐ:",
    "সর্বমোট টাকা": "Ne Nyinaa Pɛpɛɛpɛ",
    "উপমোট:": "Ne Fa Bi:",
    "ছাড়:": "Te So:",
    "পরিশোধিত:": "Wɔatua:",
    "বকেয়া:": "Aka:",

    # Online Storefront
    "সব পণ্য": "Nnoɔma Nyinaa",
    "স্পেশাল ডিল": "Deals a Ɛyɛ Soronko",
    "মুদি ও খাদ্য": "Nnuane & Provisions",
    "দুধ ও ডেইরি": "Nufusuo & Dairy",
    "স্ন্যাক্স ও বিস্কুট": "Biscuits & Snacks",
    "জুস ও পানীয়": "Nsa & Anonneɛ",
    "প্রসাধন ও রূপচর্চা": "Ahosiesie Nnoɔma",
    "গৃহস্থালী ও ক্লিনিং": "Efie & Ahotew Nnoɔma",
    "তথ্য পূরণ করুন": "Hyɛ Nsɛm No Mu",
    "দয়া করে আপনার নাম, মোবাইল এবং ঠিকানা লিখুন।": "Yɛsrɛ wo, kyerɛw wo din, fon nɔma ne beaeɛ a wowɔ.",
    "অর্ডার সম্পন্ন হয়েছে!": "Order No Ayɛ Yie Pɛpɛɛpɛ!",
    "পূর্ববর্তী পৃষ্ঠায় ফিরুন": "San Kɔ Akyi",
    "ডেলিভারি এলাকা:": "De kɔ:",
    "৪৫-৬০ মিনিট": "Dɔnhwerew 45 Express",
    "গ্রেট সুপার সেভিংস সেল": "AKORA KƐSEƐ SALES",
    "সকল অফার দেখুন": "Hwɛ Deals Nyinaa",
    "আজকের সেরা ডিল (Deals of the Day)": "Ɛnnɛ Deals a Ɛyɛ Soronko",
    "সীমিত সময়ের জন্য বিশেষ মূল্যছাড়": "Tekyerɛma titiriw berɛ kakra bi mu",
    "সব ডিল দেখুন >": "Hwɛ deals nyinaa >",
    "যোগ করুন": "Fa Ka Ho",
    "জনপ্রিয় (Featured)": "Nea Nnipa Pɛ Pa Ara",
    "জনপ্রিয়": "Nea Nnipa Pɛ Pa Ara",
    "কম দাম আগে": "Boɔ a Ɛba Fam Kane",
    "বেশি দাম আগে": "Boɔ a Ɛkɔ Anim Kane",
    "সেরা রেটিং": "Gyinabea a Ɛkɔ Anim",
    "কাল ডেলিভারি": "Yɛde bɛbrɛ wo ɔkyena",
    "চেকআউট করুন": "Tua Ka Seesei",
    "মোট প্রদেয় টাকা:": "Order Nyinaa:",

    # Banking & Loans
    "কারেন্ট": "Current Account",
    "মার্চেন্ট ওয়ালেট": "Merchant MoMo Wallet",
    "ইসলামিক": "Commercial Business",
    "নতুন ব্যাংক অ্যাকাউন্ট খুলুন": "Bue Sikakorabea Akawnt Foforɔ",
    "অ্যাকাউন্টে টাকা গ্রহণ করুন": "Gye Sika No Wɔ Sikakorabea",

    # Products & Reselling
    "সকল ক্যাটাগরি": "Nkyekyɛmu Nyinaa",
    "ইলেকট্রনিক্স": "Anyinam Nnoɔma",
    "মুদি ও অর্গানিক": "Provisions & Nnuane",
    "ফ্যাশন": "Ntoma & Ntadehyɛ",
    "এক্সপোর্ট": "Export",
    "ইমপোর্ট": "Import",
    "বারকোড প্রিন্ট": "Tintim Barcode",
    "পণ্যের নাম": "Nnoɔma Din",
    "ক্রয় মূল্য": "Boɔ a Wɔtɔeɛ",
    "বিক্রয় মূল্য": "Boɔ a Wɔtɔn",
    "স্টকের পরিমাণ": "Akorae Dodoɔ",
    "সর্বনিম্ন স্টক": "Akorae a Ɛba Fam Pa Ara",
    "একক": "Unit",

    # Reviews & Ratings
    "উত্তর প্রকাশ করা হয়েছে!": "Mmuaeɛ No Akɔ!",
    "গ্রাহক আপনার উত্তর দেখতে পাবেন।": "Otɔfoɔ no betumi ahwɛ mmuaeɛ no.",
    "রেটিং লিংক পাঠানো হয়েছে!": "Review Link No Akɔ!",
    "আজকের সকল ক্রেতার মোবাইলে SMS রেটিং লিংক পাঠানো হয়েছে।": "Wɔamane review link no akɔ nnɛ atɔfoɔ fon so.",
    "ব্যবসায়িক রেটিং ও সুনাম": "Adwuma Gyinabea & Abodin",
    "ভেরিফায়েড শপ": "Dukan a Wɔagye Atom",
    "গ্রাহক প্রতিক্রিয়া, স্কোর ও বিশ্বাসযোগ্যতা রিপোর্ট": "Atɔfoɔ adwene, gyinabea ne ahotosoɔ amanneɛbɔ",
    "টি ভেরিফায়েড রিভিউ": "atɔfoɔ nsɛm a wɔagye atom",
    "৯৮.৭% সন্তুষ্ট গ্রাহক": "98.7% Atɔfoɔ Ani Agye",
    "সঠিক ডিজিটাল ওজন": "Digital Kɛseɛ Pɛpɛɛpɛ",
    "অন-টাইম ডেলিভারি": "Kɔmafoɔ a Wɔba Pɛpɛɛpɛ",
    "স্বচ্ছ বাকির খাতা": "Aka Kyerɛwtohɔ a Emu Da Hɔ",
    "ফিল্টার:": "Yi Mu:",
    "সকল": "Nyinaa",
    "এসএমএসে রেটিং চান": "Bisa Review Wɔ SMS So",
    "সাম্প্রতিক গ্রাহক রিভিউ": "Atɔfoɔ Nsɛm a Wɔaka Nnansa Yi",
    "মালিকের উত্তর": "Wura Mmuaeɛ",
    "গ্রাহকের মতামতের উত্তর লিখুন...": "Kyerɛw mmuaeɛ kɔma otɔfoɔ no...",
    "বাতিল": "Gyae (Cancel)",
    "প্রকাশ করুন": "Pae Mu Kyerɛ (Publish)",
    "উত্তর দিন": "Bua Review No",

    # AI Scanner
    "রাঁধুনী হলুদ গুঁড়া ১০০গ্রাম": "Tasty Tom Tomato Mix 70g",
    "হস্তনির্মিত মসলা": "Ghana Provisions",
    "ফ্রেশ সয়াবিন তেল ১লিটার": "Frytol Vegetable Cooking Oil 1L",
    "প্রাণ ফ্রুটো ম্যাঙ্গো ২৫০মি.লি.": "Don Simon Multifrutas Juice 1L",
    "এসিআই পিওর ভ্যাকিউম লবণ ১কেজি": "Annapurna Iodized Salt 500g",
    "ম্যাগি ২-মিনিট মাসালা নুডলস ৪-প্যাক": "Indomie Instant Noodles 70g",
    "ডেটোল অরিজিনাল সাবান ৭৫গ্রাম": "Geisha Soap Shea Butter 175g",
    "ডানো ডেইলি পুষ্টি গুঁড়ো দুধ ৫০০গ্রাম": "Ideal Evaporated Milk 160g",
    "ইস্পাহানি মির্জাপুর সেরা পাতা চা ৪০০গ্রাম": "Lipton Yellow Label Tea 25 Bags",
    "এআই ক্যামেরা স্ক্যান চালান": "AI Camera Scan",
    "স্টক বৃদ্ধি সফল!": "Akorae No Ayɛ Kɛseɛ Yie!",
    "এআই স্ক্যান রি-স্টক": "AI Scan Restock",
    "পণ্যটি আগেই ছিল — স্টক আপডেট হয়েছে!": "Nnoɔma No Wɔ Hɔ Dada — Akorae Ayɛ Foforɔ!",
    "এআই স্ক্যানে নতুন পণ্য যুক্ত হয়েছে!": "Nnoɔma Foforɔ Aka Ho Wɔ AI Scan So!",
    "ক্যামেরা প্রস্তুত হচ্ছে অথবা ব্রাউজার অ্যাক্সেস দিন": "Camera resiesie ne ho...",
    "লাইভ ডিটেকশন চালু": "Live AI Detection Reyɛ Adwuma",
    "বাংলাদেশ FMCG ডাটাবেজ": "Ghana FMCG Retail Engine",
    "প্যাকেটের নাম বা গায়ে ফোকাস করুন": "Hwɛ nnoɔma no din anaa ahyɛnsodeɛ no so",
    "পণ্যের নাম, ওজন (যেমন 100g, 1L) ও দাম স্বয়ংক্রিয় রিড হবে": "Ɛhunu Din, Kɛseɛ (100g, 1L) ne Boɔ ntɛmntɛm",
    "এআই ডিটেক্ট করছে...": "AI rehwehwɛ mu...",
    "প্যাকেটের ছবি তুলুন (AI Scan)": "Twa Mfoni (AI Scan)",
    "ক্যামেরা পরিবর্তন": "Sesa Camera",
    "ছবি আপলোড": "Fa Mfoni Gu So",
    "দ্রুত টেস্ট করতে স্যাম্পল প্যাকেট সিলেক্ট করুন:": "Sɔ hwɛ: Fa nnoɔma yi yɛ nhwɛsoɔ:",
    "রিয়েল রিটেল পণ্য": "Ghana FMCG Nnoɔma",
    "ব্র্যান্ড:": "Brand:",
    "প্যাকেট সাইজ:": "Kɛseɛ:",
    "পাইকারি মূল্য (Buy)": "Boɔ a Wɔtɔeɛ (Buy)",
    "খুচরা মূল্য (Sell)": "Boɔ a Wɔtɔn (Sell)",
    "লাভের মার্জিন": "Mfasoɔ %",
    "স্টক ও মূল্য নিশ্চিত করুন:": "Gye Dodoɔ ne Boɔ Tom:",
    "স্টক ইন পরিমাণ": "Akorae a Wode Reba",
    "প্রাথমিক স্টক": "Akorae a Ɛwɔ Hɔ",
    "পরিমাণ (পিস)": "Dodoɔ (Pcs)",
    "পুনরায় স্ক্যান": "San Scan Bio",
    "স্টকে যোগ করুন": "Fa Ka Akorae Ho",
    "প্রোডাক্ট লিস্টে যুক্ত করুন": "Fa Ka Nnoɔma Din Ho",

    # Notifications
    "বিজ্ঞপ্তি ও সতর্কতা": "Nkaebɔ & Kɔkɔbɔ",
    "টি অপঠিত নোটিফিকেশন রয়েছে": "nkaebɔ a wonkenkanee da",
    "সকল নোটিফিকেশন পড়া সম্পন্ন": "Woakenkan nkaebɔ nyinaa awie",
    "সব পড়া হিসেবে চিহ্নিত": "Hyɛ sɛ woakenkan nyinaa",
    "সকল বিজ্ঞপ্তি": "Nkaebɔ Nyinaa",

    # Onboarding
    "ধাপ": "Anammɔn",
    "এর": "wɔ",
}

def translate_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    original = content
    # Sort keys by length descending to match longer phrases first
    sorted_keys = sorted(TRANSLATIONS.keys(), key=lambda k: -len(k))
    for k in sorted_keys:
        v = TRANSLATIONS[k]
        content = content.replace(k, v)

    # General replacements for remaining isolated words
    word_replacements = {
        "টাকা": "Sika",
        "টাকার": "Sika",
        "পণ্য": "Nnoɔma",
        "পণ্যের": "Nnoɔma",
        "বিক্রয়": "Tɔn",
        "বিক্রির": "Tɔn",
        "লাভ": "Mfasoɔ",
        "লাভের": "Mfasoɔ",
        "বাকি": "Aka",
        "বকেয়া": "Aka",
        "খরচ": "Ka",
        "খরচের": "Ka",
        "ক্যাশ": "Sika (Cash)",
        "ব্যাংক": "Sikakorabea",
        "গ্রাহক": "Otɔfoɔ",
        "গ্রাহকের": "Otɔfoɔ",
        "গ্রাহকদের": "Atɔfoɔ",
        "সাপ্লায়ার": "Agorɔfoɔ",
        "কর্মচারী": "Adwumayɛfoɔ",
        "স্টক": "Akorae",
        "ইনভেন্টরি": "Akorae",
        "ইনভয়েস": "Invois",
        "রসিদ": "Kasaa (Receipt)",
        "রিপোর্ট": "Amanneɛbɔ",
        "সেটিংস": "Nhyehyɛeɛ",
        "বিজ্ঞপ্তি": "Nkaebɔ",
        "অ্যালার্ট": "Kɔkɔbɔ",
        "মার্কেটিং": "Dawubɔ",
        "কুরিয়ার": "Kɔmafoɔ",
        "ডেলিভারি": "Delivery",
        "অনলাইন": "Intanɛte",
        "দোকান": "Dukan",
        "দোকানের": "Dukan",
        "খুঁজুন": "Hwehwɛ",
        "যোগ": "Ka ho",
        "মুছুন": "Pepa",
        "সম্পাদনা": "Sesa",
        "সংরক্ষণ": "Kora so",
        "বাতিল": "Gyae",
        "বন্ধ": "To mu",
        "নতুন": "Foforɔ",
        "মোট": "Nyinaa",
        "সব": "Nyinaa",
        "আজ": "Ɛnnɛ",
        "কাল": "Ɔkyena",
        "সপ্তাহ": "Dapɛn",
        "মাস": "Bosome",
        "বছর": "Afe",
        "দিন": "Nna",
        "পিস": "Pcs",
        "কেজি": "kg",
        "লিটার": "L",
        "গ্রাম": "g",
    }
    for k in sorted(word_replacements.keys(), key=lambda x: -len(x)):
        content = content.replace(k, word_replacements[k])

    if content != original:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False

# Run on all files
count = 0
for root, _, files in os.walk("src"):
    for f in files:
        if f.endswith((".ts", ".tsx")):
            p = os.path.join(root, f)
            if translate_file(p):
                count += 1
print(f"Updated {count} files with Twi translations.")
